# Generated by Django 6.0.3 on 2026-03-22 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphanageprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orphanageprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='panti/profile/'),
        ),
        migrations.CreateModel(
            name='PantiMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10)),
                ('file', models.ImageField(blank=True, null=True, upload_to='panti/media/')),
                ('video_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('panti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='profiles.orphanageprofile')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
