# Generated by Django 6.0.3 on 2026-03-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_orphanageprofile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='societyprofile',
            name='jenis_kelamin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='societyprofile',
            name='nomor_telepon',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
