# Generated by Django 6.0.3 on 2026-03-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_societyprofile_jenis_kelamin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphanageprofile',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orphanageprofile',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
