# Generated by Django 6.0.3 on 2026-03-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_orphanageprofile_lat_orphanageprofile_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphanageprofile',
            name='provinsi',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
