# Generated by Django 6.0.3 on 2026-03-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_orphanageprofile_provinsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphanageprofile',
            name='kabupaten_kota',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
