# Generated by Django 6.0.3 on 2026-03-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_orphanageprofile_kabupaten_kota'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphanageprofile',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orphanageprofile',
            name='kelurahan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orphanageprofile',
            name='kode_pos',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
