# Generated by Django 6.0.3 on 2026-03-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_orphanageprofile_kecamatan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='societyprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='masyarakat/profile/'),
        ),
    ]
