# Generated by Django 6.0.3 on 2026-03-25 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_societyprofile_jenis_kelamin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_panti', models.CharField(max_length=255)),
                ('jumlah', models.IntegerField()),
                ('metode_pembayaran', models.CharField(blank=True, max_length=50)),
                ('no_referensi', models.CharField(blank=True, max_length=50)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('panti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donasi_masuk', to='profiles.orphanageprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
    ]
