# Generated by Django 6.0.3 on 2026-04-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebutuhan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kebutuhanitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
