# Generated by Django 6.0.3 on 2026-03-22 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('profiles', '0002_orphanageprofile_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisPemasukan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('panti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jenis_pemasukan', to='profiles.orphanageprofile')),
            ],
            options={
                'ordering': ['nama'],
                'unique_together': {('panti', 'nama')},
            },
        ),
        migrations.CreateModel(
            name='Pemasukan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15)),
                ('catatan', models.TextField(blank=True, default='')),
                ('tanggal', models.DateField()),
                ('jenis_pemasukan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='finance.jenispemasukan')),
                ('panti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pemasukan', to='profiles.orphanageprofile')),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Pengeluaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15)),
                ('catatan', models.TextField(blank=True, default='')),
                ('tanggal', models.DateField()),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengeluaran', to='inventory.inventorycategory')),
                ('panti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengeluaran', to='profiles.orphanageprofile')),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
    ]
