# Generated by Django 6.0.3 on 2026-04-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pemasukan',
            options={'ordering': ['-tanggal', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pengeluaran',
            options={'ordering': ['-tanggal', '-created_at']},
        ),
        migrations.AddField(
            model_name='pemasukan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pengeluaran',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
