# Generated by Django 6.0.3 on 2026-03-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetpending'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='nomor_telepon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
