# Generated by Django 6.0.3 on 2026-03-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pendingregistration_nomor_telepon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='provinsi_panti',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
