# Generated by Django 6.0.3 on 2026-03-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pendingregistration_provinsi_panti'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='kabupaten_kota_panti',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='lat_panti',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='lng_panti',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
