# Generated by Django 6.0.3 on 2026-03-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pendingregistration_kabupaten_kota_panti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='kecamatan_panti',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='kelurahan_panti',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='kode_pos_panti',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
