# Generated by Django 6.0.3 on 2026-03-22 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_orphanageprofile_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pekerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('divisi', models.CharField(max_length=100)),
                ('posisi', models.CharField(max_length=100)),
                ('panti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pekerja', to='profiles.orphanageprofile')),
            ],
            options={
                'ordering': ['divisi', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='Penghuni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('tahun_lahir', models.PositiveIntegerField()),
                ('jenis_kelamin', models.CharField(choices=[('laki-laki', 'Laki-laki'), ('perempuan', 'Perempuan')], max_length=20)),
                ('panti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penghuni', to='profiles.orphanageprofile')),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
    ]
