# Generated by Django 6.0.3 on 2026-04-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stoklaroran'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='daily_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stoklaporan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
