// Mocks generated by Mockito 5.4.6 from annotations
// in ruangpeduliapp/test/widget/masyarakat/screens/search/search_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:ruangpeduliapp/data/profile_api.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSocietyProfileModel_0 extends _i1.SmartFake
    implements _i2.SocietyProfileModel {
  _FakeSocietyProfileModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePantiProfileModel_1 extends _i1.SmartFake
    implements _i2.PantiProfileModel {
  _FakePantiProfileModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePantiMediaModel_2 extends _i1.SmartFake
    implements _i2.PantiMediaModel {
  _FakePantiMediaModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileApi extends _i1.Mock implements _i2.ProfileApi {
  MockProfileApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.SocietyProfileModel?> fetchMasyarakatProfile(int? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchMasyarakatProfile,
          [userId],
        ),
        returnValue: _i3.Future<_i2.SocietyProfileModel?>.value(),
      ) as _i3.Future<_i2.SocietyProfileModel?>);

  @override
  _i3.Future<_i2.SocietyProfileModel> updateMasyarakatProfile(
    int? profileId, {
    String? namaPengguna,
    String? alamat,
    String? username,
    String? email,
    String? nomorTelepon,
    String? jenisKelamin,
    _i4.File? profilePicture,
    bool? removeProfilePicture = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMasyarakatProfile,
          [profileId],
          {
            #namaPengguna: namaPengguna,
            #alamat: alamat,
            #username: username,
            #email: email,
            #nomorTelepon: nomorTelepon,
            #jenisKelamin: jenisKelamin,
            #profilePicture: profilePicture,
            #removeProfilePicture: removeProfilePicture,
          },
        ),
        returnValue: _i3.Future<_i2.SocietyProfileModel>.value(
            _FakeSocietyProfileModel_0(
          this,
          Invocation.method(
            #updateMasyarakatProfile,
            [profileId],
            {
              #namaPengguna: namaPengguna,
              #alamat: alamat,
              #username: username,
              #email: email,
              #nomorTelepon: nomorTelepon,
              #jenisKelamin: jenisKelamin,
              #profilePicture: profilePicture,
              #removeProfilePicture: removeProfilePicture,
            },
          ),
        )),
      ) as _i3.Future<_i2.SocietyProfileModel>);

  @override
  _i3.Future<List<_i2.PantiProfileModel>> fetchAllPanti() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAllPanti,
          [],
        ),
        returnValue: _i3.Future<List<_i2.PantiProfileModel>>.value(
            <_i2.PantiProfileModel>[]),
      ) as _i3.Future<List<_i2.PantiProfileModel>>);

  @override
  _i3.Future<_i2.PantiProfileModel> fetchPantiProfile(int? pantiId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPantiProfile,
          [pantiId],
        ),
        returnValue:
            _i3.Future<_i2.PantiProfileModel>.value(_FakePantiProfileModel_1(
          this,
          Invocation.method(
            #fetchPantiProfile,
            [pantiId],
          ),
        )),
      ) as _i3.Future<_i2.PantiProfileModel>);

  @override
  _i3.Future<_i2.PantiProfileModel> updatePantiProfile(
    int? pantiId, {
    String? namaPanti,
    String? alamatPanti,
    String? nomorPanti,
    String? description,
    String? username,
    String? email,
    String? password,
    _i4.File? profilePicture,
    bool? removeProfilePicture = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePantiProfile,
          [pantiId],
          {
            #namaPanti: namaPanti,
            #alamatPanti: alamatPanti,
            #nomorPanti: nomorPanti,
            #description: description,
            #username: username,
            #email: email,
            #password: password,
            #profilePicture: profilePicture,
            #removeProfilePicture: removeProfilePicture,
          },
        ),
        returnValue:
            _i3.Future<_i2.PantiProfileModel>.value(_FakePantiProfileModel_1(
          this,
          Invocation.method(
            #updatePantiProfile,
            [pantiId],
            {
              #namaPanti: namaPanti,
              #alamatPanti: alamatPanti,
              #nomorPanti: nomorPanti,
              #description: description,
              #username: username,
              #email: email,
              #password: password,
              #profilePicture: profilePicture,
              #removeProfilePicture: removeProfilePicture,
            },
          ),
        )),
      ) as _i3.Future<_i2.PantiProfileModel>);

  @override
  _i3.Future<List<_i2.PantiMediaModel>> fetchPantiMedia(int? pantiId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPantiMedia,
          [pantiId],
        ),
        returnValue: _i3.Future<List<_i2.PantiMediaModel>>.value(
            <_i2.PantiMediaModel>[]),
      ) as _i3.Future<List<_i2.PantiMediaModel>>);

  @override
  _i3.Future<_i2.PantiMediaModel> uploadPantiMedia(
    int? pantiId, {
    _i4.File? file,
    String? videoUrl,
    String? mediaType = 'photo',
    int? order = 0,
    String? title = '',
    String? description = '',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPantiMedia,
          [pantiId],
          {
            #file: file,
            #videoUrl: videoUrl,
            #mediaType: mediaType,
            #order: order,
            #title: title,
            #description: description,
          },
        ),
        returnValue:
            _i3.Future<_i2.PantiMediaModel>.value(_FakePantiMediaModel_2(
          this,
          Invocation.method(
            #uploadPantiMedia,
            [pantiId],
            {
              #file: file,
              #videoUrl: videoUrl,
              #mediaType: mediaType,
              #order: order,
              #title: title,
              #description: description,
            },
          ),
        )),
      ) as _i3.Future<_i2.PantiMediaModel>);

  @override
  _i3.Future<List<_i2.PantiUploadedVideo>> fetchAllPantiVideos() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAllPantiVideos,
          [],
        ),
        returnValue: _i3.Future<List<_i2.PantiUploadedVideo>>.value(
            <_i2.PantiUploadedVideo>[]),
      ) as _i3.Future<List<_i2.PantiUploadedVideo>>);

  @override
  _i3.Future<void> deletePantiMedia(
    int? pantiId,
    int? mediaId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePantiMedia,
          [
            pantiId,
            mediaId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
